### ISSUE TITLE
Local reference to jQuery included in index.html differs from external reference used in preceding labs

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-jquery-event-listeners-readme#10]
The index.html for this lab includes the following local reference to jQuery:

---- js/jquery-2.1.1.min.js

However, preceding labs reference an external source (Google) for jQuery:

---- http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js

**Comment by gj** [comment]
Not sure why this would be a problem to begin with, but [this merged PR](https://github.com/learn-co-curriculum/jquery-selectors-readme/pull/8) introduced the local (non-CDN) source for jQuery in the [jQuery Selectors Readme](https://github.com/learn-co-curriculum/jquery-selectors-readme).

cc: @AnnJohn

**Comment by JessRudder** [comment]
Going to close this issue since it's non-breaking.
