### ISSUE TITLE
Isn't 'g' 103 instead of 71 (ASCII characters)?

### ISSUE THREAD

**Issue by marineb** [learn-co-curriculum/js-jquery-event-listeners-readme#11]
Reference: http://www.theasciicode.com.ar/ascii-printable-characters/lowercase-letter-g-minuscule-ascii-code-103.html. 

Now, I notice the link you're referring to in the exercise says something different: http://keycode.info/

**Comment by gj** [comment]
From [the jQuery API documentation](http://api.jquery.com/keypress/):

> Note that keydown and keyup provide a code indicating which key is pressed, while keypress indicates which character was entered. For example, a lowercase "a" will be reported as 65 by keydown and keyup, but as 97 by keypress. An uppercase "A" is reported as 65 by all events.

If you'd like to test out which keycodes are generated by which keystrokes, I recommend the W3C's [Keyboard Events and Codes](https://www.w3.org/2002/09/tests/keys.html) tool. It's a bit more in-depth (if a lot less pretty) than the [keycode.info](http://keycode.info/) site linked in the lesson.

**Comment by JessRudder** [comment]
Readme was updated to request "G" instead of "g"
